apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
          argocd.argoproj.io/sync-wave: "-30"

  - target:
      kind: OperatorGroup
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-20"

  - target:
      kind: Subscription
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-10"

  - target:
      kind: LVMCluster
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

  - target:
      kind: ArgoCD
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

  - target:
      kind: NMState
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

  - target:
      kind: MetalLB
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

