---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/openstack-gitops/rhoso-gitops/components/argocd/annotations?ref=cleaning
  - https://github.com/openstack-gitops/rhoso-gitops/components/base/controlplane?ref=cleaning

# Add needed patches according to your infrastructure
