apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - ../../../cluster/common/console

# patch the default console contents and add the OpenShift Console GitOps interface
patches:
  - target:
      group: operator.openshift.io
      kind: Console
      version: v1
      name: cluster
    path: patches/console-plugin-gitops.yaml
