apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhoso-placement
  namespace: openshift-gitops
spec:
  clusterSets:
  - rhoso
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: In
          values:
          - OpenShift
        - key: clusterType
          operator: In
          values:
          - rhoso
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
