---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  name: subscribe-external-secrets-operator
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      components:
        - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=v0.1.1
    path: resources/external-secrets-operator
    repoURL: https://github.com/openstack-k8s-operators/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
