---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  name: subscribe-vault-secrets-operator
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      components:
        - https://github.com/openstack-gitops/rhoso-gitops/components/argocd/annotations
    path: resources/vault-secrets-operator
    repoURL: https://github.com/openstack-gitops/rhoso-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
