---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: internal-git-repo
    namespace: openshift-gitops
    envs:
      - gitrepo.env

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: internal-git-repo
        namespace: openshift-gitops
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository

resources:
  - gitops-subscribe.yaml
  - openstack-clusterrole.yaml
  - argocd-openshift-gitops.yaml
