---
apiVersion: batch/v1
kind: Job
metadata:
  name: clean-observability
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: clean-observability-csv
          image: registry.redhat.io/openshift4/ose-cli@sha256:ef83967297f619f45075e7fd1428a1eb981622a6c174c46fb53b158ed24bed85  # :latest as of 2026-07-06
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          command: ['sh', '-c']
          args:
            - |-
              oc get csv -A | \
              awk '/cluster-observability-operator/ {print $1, $2}' | \
              sort -u | \
              xargs --no-run-if-empty -n2 sh -c 'oc -n $0 delete csv $1'
