apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: common-metallb
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/common/metallb
    repoURL: https://github.com/openstack-k8s-operators/architecture
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            kind: Namespace
          patch: |-
            - op: add
              path: /metadata/labels
              value:
                argocd.argoproj.io/managed-by: openshift-gitops
  syncPolicy:
    automated: {}
