---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - openstack-controlplane.yaml
  - openstack-ipaddresspools.yaml
  - openstack-l2advertisement.yaml
  - openstack-net-attach-def.yaml
  - openstack-netconfig.yaml
  - openstack-nncp.yaml
