---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-services
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dataplane-services
          image: registry.redhat.io/openshift4/ose-cli:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          command: ['sh', '-c']
          args:
            - |
              oc -n openstack delete OpenStackDataPlaneService --all
