---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: MultiClusterEngine.v1.multicluster.openshift.io
  name: default
  namespace: multicluster-engine
spec:
  targetNamespaces:
    - multicluster-engine
  upgradeStrategy: Default
