---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../config/namespace
  - ../../overlays/basic-auth_tls
namePrefix: baremetal-operator-
namespace: baremetal-operator-system
secretGenerator:
  - envs:
      - ironic-htpasswd
    name: ironic-htpasswd
    type: Opaque
components:
  - ../../components/mariadb
configMapGenerator:
  - behavior: create
    envs:
      - ironic_bmo_configmap.env
    name: ironic-bmo-configmap
