---
apiVersion: v1
items:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: openshift-storage
      namespace: openshift-storage
    spec:
      targetNamespaces:
        - openshift-storage
      upgradeStrategy: Default
kind: List
metadata:
  resourceVersion: ""
