---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  # Remote refs (for CI/ArgoCD):
  - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=v0.1.0
  - https://github.com/openstack-k8s-operators/gitops/components/rhoso/controlplane/networking?ref=v0.1.0
  # Local paths (for "kustomize build" testing):
  # - ../../components/argocd/annotations
  # - ../../components/rhoso/controlplane/networking

# Add needed patches according to your infrastructure
