---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../community
  - namespace.yaml
  - operatorgroup.yaml
patches:
  - path: patch-subscription-redhat.json
    target:
      kind: Subscription
      name: external-secrets-operator
      namespace: openshift-operators
