---
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      gatewayConfig:
        ipForwarding: Global
