---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../namespace
namespace: baremetal-operator-system
components:
  - ../../components/basic-auth
  - ../../components/tls
secretGenerator:
  - files:
      - username=ironic-username
      - password=ironic-password
    name: ironic-credentials
    type: Opaque
configMapGenerator:
  - behavior: create
    envs:
      - ironic.env
    name: ironic
