---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-openstack
rules:
  - apiGroups:
      - core.openstack.org
    resources:
      - openstackcontrolplanes
    verbs:
      - '*'
  - apiGroups:
      - network.openstack.org
    resources:
      - netconfigs
    verbs:
      - '*'
  - apiGroups:
      - k8s.cni.cncf.io
    resources:
      - network-attachment-definitions
    verbs:
      - '*'
  - apiGroups:
      - nmstate.io
    resources:
      - nmstates
      - nodenetworkconfigurationpolicies
    verbs:
      - '*'
  - apiGroups:
      - metallb.io
    resources:
      - metallbs
      - l2advertisements
      - ipaddresspools
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - metal3.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - lvm.topolvm.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - 'managedclustersets'
      - 'managedclustersetbindings'
    verbs:
      - '*'
  - apiGroups:
      - multicluster.openshift.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - baremetal.openstack.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - secrets.hashicorp.com
    resources:
      - 'vaultstaticsecrets'
    verbs:
      - '*'
  - apiGroups:
      - operator.openstack.org
    resources:
      - 'openstacks'
    verbs:
      - '*'
  - apiGroups:
      - dataplane.openstack.org
    resources:
      - 'openstackdataplanedeployments'
      - 'openstackdataplanenodesets'
      - 'openstackdataplaneservices'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-openstack
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
