apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: openstack-operators
    namespace: openstack-operators
  spec:
    upgradeStrategy: Default
kind: List
metadata:
  resourceVersion: ""
