---
name: file-consistency
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.yml"
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install yaml-lint
        run: pip install yamllint

      - name: Run yaml-lint
        run: yamllint -c .yamllint.yml -s .
