---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  name: subscribe-gitops
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/initialize/gitops/subscribe
    repoURL: https://github.com/openstack-gitops/rhoso-gitops.git
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            kind: Namespace
          patch: |-
            - op: add
              path: /metadata/labels
              value:
                argocd.argoproj.io/managed-by: openshift-gitops
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: enable-gitops
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/initialize/gitops/enable
    repoURL: https://github.com/openstack-gitops/rhoso-gitops.git
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            kind: Namespace
          patch: |-
            - op: add
              path: /metadata/labels
              value:
                argocd.argoproj.io/managed-by: openshift-gitops
  syncPolicy:
    automated: {}
